aws.region=us-east-1

agentcore.gateway.name=gateway-pet-store-api
agentcore.gateway.role-name=gateway-pet-store-api-role
agentcore.gateway.target-name=rest-pet-store-api
agentcore.gateway.openapi-s3-uri=s3://8744-open-api-specifications/openapi-pet-store-api.yaml
agentcore.gateway.wait-timeout-seconds=600
