aws.region=us-east-1

agentcore.gateway.name=gateway-pet-store-api
agentcore.gateway.role-name=gateway-pet-store-api-role
agentcore.gateway.target-name=rest-pet-store-api
agentcore.gateway.openapi-s3-uri=s3://8744-open-api-specifications/openapi-pet-store-api.yaml
agentcore.gateway.wait-timeout-seconds=600

agentcore.runtime.name=pet_store_agent
agentcore.runtime.role-name=pet-store-agent-runtime-role
agentcore.runtime.container-uri=884457518744.dkr.ecr.us-east-1.amazonaws.com/spring-ai-agent:latest
agentcore.runtime.bedrock-model-id=us.amazon.nova-2-lite-v1:0
agentcore.runtime.idle-session-timeout-seconds=180
agentcore.runtime.max-lifetime-seconds=3600
agentcore.runtime.wait-timeout-seconds=900
